env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
