language: node_js
node_js:
  - "12.19"

script:
    - echo "TST"

deploy:
  provider: npm
  api_token: 
    secure: Z4ZRZdA+fN6tHfa4iiYfok6R/MY+hUw9eg0rQBs4YzpYqUSS0gW5+lhp0Ij3XOSXR1MxYXo6p3l4srKtzS1WQUj6fFlmwQxRh9QARq+LypuzFEfwXJIXfmvHFOevG8nvPbhKY3vdoNEQ2BMCQ1DXsgMeqpfF1jwnw9BFgWWrq3hs4MgXNNdlOcxcFK1vjHJSXW3swuceHWDxo/7dmRCfcK8HZwFnRmBCqhWEqA8SA22w62V9V7zAaGgBbbwBZGUEekPGEvo4V3DnSaCDi7xaBzrW6POmjuhgJxJIX0/LdRTOt0vZTKqnJvgEZFO8jzRZVALhbOMhUeeZXyDB5RLjoA8xO/0CYiEqKXj7qAgMA2OmDThd1Ro/qqJjG9hi2ek1S5QPtQ4T73413fb+D1RvvkE06gdJtGyWii5VMXhFim0O7lmkGnRqv71OYaykUxQcFZRmfA4osnQtpjRByO43wpymdMN9BR0qCMt0pRw0ee/B3MUeFKs4WKp+xAkUIEXlrZNzgdPt0Rb0SMWniQFDtLXIWqhA3YTLEOJf0gaWAKBQeel+9HWY+rZxB/NAHoQolf3JCK1VLeL7fc24iv2rCAxSXAyirZFXMmcfdO9+IvDV7enET9xwaHs6ndHf65dwTH2tXafGbJ4S2uguSV61GIswJ0X54qlj1U3FV6GAlWc=%
  edge: true
  dry_run: true
  skip_cleanup: true