on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: 
      - uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}

